name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: simptipserver            # Your Azure WebApp name
  AZURE_WEBAPP_PACKAGE_PATH: './server'       # Path to your server directory
  NODE_VERSION: '18.x'                        # Node.js version

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      # Step 3: Install dependencies
      - name: Install Dependencies
        working-directory: ./server
        run: npm install

      # Step 4: Set Development Environment Variables
      - name: Set Development Environment
        working-directory: ./server
        run: |
          echo "NODE_ENV=development" > .env
          echo "API_URL=https://dev.api.simptipserver.com" >> .env

      # Step 5: Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
