name: Deploy Node.js Express Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup SSH Agent and add the SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      # Step 3: Copy files to EC2 using SCP
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "server/"
          target: "/var/www/simpBack/"

      # Step 4: Execute Deployment Script on EC2
      - name: Execute Deployment Script on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e

            echo "Starting Deployment Script"

            # Navigate to the application directory
            cd /var/www/simpBack

            # List files to verify transfer
            echo "Listing files in /var/www/simpBack:"
            ls -la

            # Ensure Node.js is installed
            if ! command -v node &> /dev/null; then
              echo "Node.js not found. Installing..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js is already installed."
            fi

            # Ensure npm is installed
            if ! command -v npm &> /dev/null; then
              echo "npm is not installed. Exiting."
              exit 1
            fi

            # Install PM2 globally if not already installed
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing..."
              sudo npm install -g pm2
            else
              echo "PM2 is already installed."
            fi

            # Install dependencies
            echo "Installing dependencies..."
            npm install || { echo "npm install failed"; exit 1; }

            # Optional: Build your application if needed
            # echo "Building the application..."
            # npm run build || { echo "Build failed"; exit 1; }

            # Restart the application with PM2 using npm scripts
            echo "Starting the application with PM2..."
            pm2 delete simpBack || true # Ignore errors if the process doesn't exist

            # Start the main server
            pm2 start npm --name "simpBack-server" -- start

            # Start the worker
            pm2 start npm --name "simpBack-worker" -- run worker

            # Optionally, you can start additional workers or other scripts
            # pm2 start npm --name "simpBack-worker-dev" -- run worker-dev

            pm2 save

            echo "Deployment Complete"
