name: Deploy Node.js Express Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            export DEBIAN_FRONTEND=noninteractive

            # Ensure Node.js is installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Create application directory
            APP_DIR="/var/www/simpBack"
            sudo mkdir -p $APP_DIR
            sudo chown -R $USER:$USER $APP_DIR
            cd $APP_DIR

            # Stop running app
            pm2 stop all || echo "No app running"

            # Clean only the application directory, excluding sensitive paths
            find $APP_DIR -mindepth 1 -not -path "$APP_DIR/proc/*" -delete

            # Sync application files
            rsync -av --exclude='/proc' $GITHUB_WORKSPACE/server/ $APP_DIR/

            # Install dependencies
            cd $APP_DIR
            npm install

            # Start application with PM2
            pm2 start server.js --name simpBack --watch
            pm2 save

      - name: Sync Application to S3
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            AWS_BUCKET_NAME="simp-tip-server"
            AWS_REGION="us-east-1"
            APP_DIR="/var/www/simpBack"

            # Ensure unzip is installed
            if ! command -v unzip &> /dev/null; then
              sudo apt-get update && sudo apt-get install -y unzip
            fi

            # Install AWS CLI if not already installed
            if ! command -v aws &> /dev/null; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              export PATH=$PATH:/usr/local/bin/aws
            fi

            # Sync application files to S3
            aws s3 sync $APP_DIR s3://$AWS_BUCKET_NAME/ --region $AWS_REGION
