name: Deploy Node.js Express Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e

            echo "Starting Deployment Script"

            # Ensure Node.js and npm are installed
            if ! command -v node &> /dev/null; then
              echo "Node.js not found. Installing..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js is already installed."
            fi

            if ! command -v npm &> /dev/null; then
              echo "npm is not installed. Exiting."
              exit 1
            fi

            # Install PM2 globally if not already installed
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 not found. Installing..."
              sudo npm install -g pm2
            else
              echo "PM2 is already installed."
            fi

            # Application directory on the server
            echo "Creating application directory..."
            sudo mkdir -p /var/www/simpBack
            sudo chown -R $USER:$USER /var/www/simpBack

            # Sync files to the application directory
            echo "Syncing files to /var/www/simpBack..."
            rsync -avz --delete --exclude='node_modules' ~/actions-runner/_work/simpBack/server/ /var/www/simpBack/ || { echo "rsync failed"; exit 1; }

            # Navigate to the application directory
            cd /var/www/simpBack

            # Check for package.json
            if [ ! -f package.json ]; then
              echo "Error: package.json not found in /var/www/simpBack. Exiting."
              exit 1
            fi

            # Install dependencies
            echo "Installing dependencies..."
            npm install || { echo "npm install failed"; exit 1; }

            # Check for server.js
            if [ ! -f server.js ]; then
              echo "Error: server.js not found in /var/www/simpBack. Exiting."
              exit 1
            fi

            # Restart the application with PM2
            echo "Starting the application with PM2..."
            pm2 delete simpBack || true # Ignore errors if the process doesn't exist
            pm2 start server.js --name simpBack --watch
            pm2 save

            echo "Deployment Complete"
