name: Deploy Node.js Express Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Files for Debugging
        run: ls -R
        shell: bash
        working-directory: $GITHUB_WORKSPACE

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            export DEBIAN_FRONTEND=noninteractive

            # Ensure Node.js is installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Define application directory
            APP_DIR="/var/www/simpBack"
            SERVER_SOURCE_DIR="$GITHUB_WORKSPACE/server"

            # Debugging: List directory contents
            echo "Source directory content:"
            ls -l $SERVER_SOURCE_DIR

            # Create application directory
            sudo mkdir -p $APP_DIR
            sudo chown -R $USER:$USER $APP_DIR

            # Sync application files (only server folder)
            rsync -avz --delete --exclude='node_modules' $SERVER_SOURCE_DIR/ $APP_DIR/

            # Move into application directory
            cd $APP_DIR

            # Check if package.json exists
            if [ -f package.json ]; then
              echo "Installing dependencies..."
              npm install
            else
              echo "Error: package.json not found in $APP_DIR"
              exit 1
            fi

            # Check if server.js exists
            if [ -f server.js ]; then
              echo "Starting the application with PM2..."
              pm2 start server.js --name simpBack --watch
              pm2 save
            else
              echo "Error: server.js not found in $APP_DIR"
              exit 1
            fi
