name: Deploy Node.js Express Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      working-directory: ./server # Ensure we're working in the server directory
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Ensure correct folder on the EC2 instance
          cd /var/www/simpBack || mkdir -p /var/www/simpBack && cd /var/www/simpBack

          # Stop any running app (if using PM2)
          pm2 stop all || echo "No app running"

          # Clear existing files and sync the new files from the repository
          rm -rf *
          scp -r $GITHUB_WORKSPACE/server/* . # Copy only the server directory contents

          # Install dependencies
          npm install

          # Start the server using PM2
          pm2 start server.js --name simpBack --watch

    - name: Notify Deployment
      run: echo "Deployment completed successfully!"
