name: Deploy Node.js Express Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      working-directory: ./server
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          if ! command -v node &> /dev/null; then
            curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
            sudo yum install -y nodejs
          fi
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          mkdir -p /home/ec2-user/simpBack
          cd /home/ec2-user/simpBack
          pm2 stop all || echo "No app running"
          rm -rf *
          scp -r $GITHUB_WORKSPACE/server/* .
          npm install
          pm2 start server.js --name simpBack --watch

    - name: Notify Deployment
      run: echo "Deployment completed successfully!"
