name: Build and deploy Node.js app to Azure Web App - simptipserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          cd simpback/server
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          cd simpback/server
          zip -r ../../release.zip ./*

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simptipserver'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./release.zip

      - name: Prepare Worker WebJob
        run: |
          cd simpback/server
          zip -r ../../ttsWorker.zip workers/ttsWorker.js package.json node_modules/

      - name: Deploy Worker as WebJob
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        run: |
          USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userName=")[^"]+')
          PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userPWD=")[^"]+')
          WEBJOB_NAME="ttsWorker"
          KUDU_API_URL="https://simptipserver.scm.azurewebsites.net/api/continuouswebjobs/${WEBJOB_NAME}/upload"
          curl -X POST -u "$USERNAME:$PASSWORD" -F "file=@ttsWorker.zip" "$KUDU_API_URL"

      - name: Clean Up
        run: |
          rm release.zip ttsWorker.zip
