name: Build and deploy Node.js app to Azure Web App - simptipserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install and build
        run: |
          cd server
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d server

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'simptipserver'
          slot-name: 'Production'
          package: ./server

      - name: Prepare Worker WebJob
        run: |
          cd server
          zip -r ttsWorker.zip workers/ttsWorker.js package.json node_modules/

      - name: Deploy Worker as WebJob
        run: |
          az webapp webjob continuous add \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name simptipserver \
            --webjob-name ttsWorker \
            --file ./server/ttsWorker.zip

      - name: Clean Up
        run: |
          rm release.zip server/ttsWorker.zip
