name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd server
          npm install

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            if [ ! -d "/home/ec2-user/simpBack/server" ]; then
              git clone https://github.com/dstein131/simpBack.git /home/ec2-user/simpBack
            fi
            cd /home/ec2-user/simpBack/server
            git pull origin main

            npm install

            pm2 stop express-app || true
            pm2 start server.js --name "express-app"
            pm2 save
          EOF
