name: Build and deploy Node.js app to Azure Web App - simptipserver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          cd server
          npm ci
          npm run build --if-present

      # Step 4: Verify Installation of express
      - name: Verify express Installation
        run: |
          cd server
          if [ -d "node_modules/express" ]; then
            echo "✅ express is installed."
          else
            echo "❌ express is NOT installed."
            exit 1
          fi

      # Step 5: Zip the source code (including node_modules)
      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip ./* -x "logs/*" "*.git*" "*.github*" "README.md"

      # Step 6: Deploy the zipped artifact to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simptipserver'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./release.zip

      # Step 6.1: Force dependency installation on Azure
      - name: Post Deployment - Install Dependencies
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        run: |
          USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userName=")[^"]+')
          PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userPWD=")[^"]+')
          HOST=$(echo "$PUBLISH_PROFILE" | grep -oP '<publishProfile[^>]*publishMethod="MSDeploy"[^>]*publishUrl="\K[^"]+' | sed 's/:443$//')
          KUDU_API_URL="https://${HOST}/api/command"
          curl -u "$USERNAME:$PASSWORD" -X POST -d '{"command":"cd /home/site/wwwroot && npm install"}' -H "Content-Type: application/json" "$KUDU_API_URL"

      # Step 7: Prepare the Worker WebJob package
      - name: Prepare Worker WebJob
        run: |
          cd server
          mkdir worker_deploy
          cp workers/ttsWorker.js worker_deploy/
          cp package.json worker_deploy/
          cd worker_deploy
          npm install --omit=dev
          zip -r ../../ttsWorker.zip ./*
          if [ ! -f ../../ttsWorker.zip ]; then
            echo "Error: ttsWorker.zip was not created."
            exit 1
          fi

      # Step 8: Deploy the Worker WebJob to Azure
      - name: Deploy Worker as WebJob
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        run: |
          USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userName=")[^"]+')
          PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP '(?<=userPWD=")[^"]+')
          HOST=$(echo "$PUBLISH_PROFILE" | grep -oP '<publishProfile[^>]*publishMethod="MSDeploy"[^>]*publishUrl="\K[^"]+' | sed 's/:443$//')
          KUDU_API_URL="https://${HOST}/api/continuouswebjobs/ttsWorker/upload"
          curl -X POST -u "$USERNAME:$PASSWORD" -F "file=@ttsWorker.zip" "$KUDU_API_URL"

      # Step 9: Clean up the zipped artifacts
      - name: Clean Up
        run: |
          rm release.zip ttsWorker.zip
